// Brands the report engine spots in text, in any of the languages our
// calls use. `words` match in any letter case; `exact` only as written,
// for names that are also ordinary words ("Zoom", "Slack", "Tally").
// `slug` is the brand's Simple Icons icon (public/brands/); a brand without
// one shows a monogram in its colour. Colours come from Simple Icons.

export type Brand = Readonly<{
  key: string;
  name: string;
  slug: string | null;
  hex: string;
  /** A colour logo exists in public/brands/color.json. */
  logo?: boolean;
  words: readonly string[];
  exact: readonly string[];
}>;

export const BRANDS: readonly Brand[] = [
  {
    key: "whatsapp",
    name: "WhatsApp",
    slug: "whatsapp",
    hex: "25D366",
    logo: true,
    words: [
      "whatsapp",
      "whats app",
      "watsapp",
      "whatsaap",
      "व्हाट्सएप",
      "व्हाट्सऐप",
      "वॉट्सऐप",
      "वॉट्सएप",
      "व्हाट्सअप",
      "व्हॉट्सॲप",
      "व्हॉट्सअ‍ॅप",
    ],
    exact: [],
  },
  {
    key: "telegram",
    name: "Telegram",
    slug: "telegram",
    hex: "26A5E4",
    logo: true,
    words: ["telegram", "टेलीग्राम", "टेलिग्राम"],
    exact: [],
  },
  {
    key: "discord",
    name: "Discord",
    slug: "discord",
    hex: "5865F2",
    logo: true,
    words: ["discord", "डिस्कॉर्ड", "डिस्कोर्ड"],
    exact: [],
  },
  {
    key: "facebook",
    name: "Facebook",
    slug: "facebook",
    hex: "0866FF",
    logo: true,
    words: ["facebook", "फेसबुक", "fb page", "fb group"],
    exact: ["FB"],
  },
  {
    key: "meta",
    name: "Meta",
    slug: "meta",
    hex: "0467DF",
    words: ["meta ads", "facebook ads", "fb ads", "मेटा ऐड्स"],
    exact: ["Meta"],
  },
  {
    key: "messenger",
    name: "Messenger",
    slug: "messenger",
    hex: "0866FF",
    logo: true,
    words: ["messenger"],
    exact: [],
  },
  {
    key: "instagram",
    name: "Instagram",
    slug: "instagram",
    hex: "FF0069",
    logo: true,
    words: ["instagram", "insta", "इंस्टाग्राम", "इन्स्टाग्राम", "इंस्टा"],
    exact: [],
  },
  {
    key: "youtube",
    name: "YouTube",
    slug: "youtube",
    hex: "FF0000",
    logo: true,
    words: ["youtube", "you tube", "यूट्यूब", "युट्यूब", "यूटूब", "यु ट्यूब"],
    exact: [],
  },
  {
    key: "x",
    name: "X (Twitter)",
    slug: "x",
    hex: "000000",
    logo: true,
    words: ["twitter", "ट्विटर"],
    exact: [],
  },
  {
    key: "threads",
    name: "Threads",
    slug: "threads",
    hex: "000000",
    logo: true,
    words: [],
    exact: ["Threads"],
  },
  {
    key: "linkedin",
    name: "LinkedIn",
    slug: null,
    hex: "0A66C2",
    logo: true,
    words: ["linkedin", "linked in", "लिंक्डइन", "लिंकडइन", "लिंक्डिन"],
    exact: [],
  },
  {
    key: "snapchat",
    name: "Snapchat",
    slug: "snapchat",
    hex: "FFFC00",
    logo: true,
    words: ["snapchat", "स्नैपचैट"],
    exact: [],
  },
  {
    key: "pinterest",
    name: "Pinterest",
    slug: "pinterest",
    hex: "BD081C",
    logo: true,
    words: ["pinterest"],
    exact: [],
  },
  {
    key: "quora",
    name: "Quora",
    slug: "quora",
    hex: "B92B27",
    logo: true,
    words: ["quora"],
    exact: [],
  },
  {
    key: "reddit",
    name: "Reddit",
    slug: "reddit",
    hex: "FF4500",
    logo: true,
    words: ["reddit"],
    exact: [],
  },
  {
    key: "tiktok",
    name: "TikTok",
    slug: "tiktok",
    hex: "000000",
    logo: true,
    words: ["tiktok", "tik tok", "टिकटॉक"],
    exact: [],
  },
  {
    key: "sharechat",
    name: "ShareChat",
    slug: null,
    hex: "000000",
    words: ["sharechat", "share chat"],
    exact: [],
  },
  {
    key: "truecaller",
    name: "Truecaller",
    slug: null,
    hex: "0087FF",
    words: ["truecaller", "ट्रूकॉलर"],
    exact: [],
  },
  {
    key: "zoom",
    name: "Zoom",
    slug: "zoom",
    hex: "0B5CFF",
    logo: true,
    words: [
      "zoom call",
      "zoom meeting",
      "zoom link",
      "ज़ूम कॉल",
      "जूम कॉल",
      "ज़ूम मीटिंग",
      "जूम मीटिंग",
    ],
    exact: ["Zoom"],
  },
  {
    key: "googlemeet",
    name: "Google Meet",
    slug: "googlemeet",
    hex: "00897B",
    logo: true,
    words: ["google meet", "gmeet", "g meet", "गूगल मीट"],
    exact: [],
  },
  {
    key: "teams",
    name: "Microsoft Teams",
    slug: null,
    hex: "6264A7",
    logo: true,
    words: ["microsoft teams", "ms teams"],
    exact: [],
  },
  {
    key: "skype",
    name: "Skype",
    slug: null,
    hex: "00AFF0",
    logo: true,
    words: ["skype", "स्काइप"],
    exact: [],
  },
  {
    key: "gmail",
    name: "Gmail",
    slug: "gmail",
    hex: "EA4335",
    logo: true,
    words: ["gmail", "जीमेल"],
    exact: [],
  },
  {
    key: "googledrive",
    name: "Google Drive",
    slug: "googledrive",
    hex: "4285F4",
    logo: true,
    words: ["google drive", "gdrive", "गूगल ड्राइव"],
    exact: [],
  },
  {
    key: "googlesheets",
    name: "Google Sheets",
    slug: "googlesheets",
    hex: "34A853",
    words: ["google sheet", "google sheets", "गूगल शीट"],
    exact: [],
  },
  {
    key: "googledocs",
    name: "Google Docs",
    slug: "googledocs",
    hex: "4285F4",
    words: ["google doc", "google docs"],
    exact: [],
  },
  {
    key: "googleforms",
    name: "Google Forms",
    slug: "googleforms",
    hex: "7248B9",
    words: ["google form", "google forms", "गूगल फॉर्म"],
    exact: [],
  },
  {
    key: "googlecalendar",
    name: "Google Calendar",
    slug: "googlecalendar",
    hex: "4285F4",
    logo: true,
    words: ["google calendar"],
    exact: [],
  },
  {
    key: "googlemaps",
    name: "Google Maps",
    slug: "googlemaps",
    hex: "4285F4",
    words: ["google maps", "google map", "गूगल मैप"],
    exact: [],
  },
  {
    key: "googleads",
    name: "Google Ads",
    slug: "googleads",
    hex: "4285F4",
    logo: true,
    words: ["google ads", "adwords", "गूगल ऐड्स"],
    exact: [],
  },
  {
    key: "googlepay",
    name: "Google Pay",
    slug: "googlepay",
    hex: "4285F4",
    logo: true,
    words: ["google pay", "gpay", "g pay", "गूगल पे", "जीपे"],
    exact: [],
  },
  {
    key: "googleplay",
    name: "Google Play",
    slug: "googleplay",
    hex: "414141",
    logo: true,
    words: ["play store", "playstore", "google play", "प्ले स्टोर"],
    exact: [],
  },
  {
    key: "google",
    name: "Google",
    slug: "google",
    hex: "4285F4",
    logo: true,
    words: ["google", "गूगल"],
    exact: [],
  },
  {
    key: "gemini",
    name: "Google Gemini",
    slug: "googlegemini",
    hex: "8E75B2",
    logo: true,
    words: ["google gemini", "gemini ai"],
    exact: [],
  },
  {
    key: "chatgpt",
    name: "ChatGPT",
    slug: null,
    hex: "10A37F",
    logo: true,
    words: ["chatgpt", "chat gpt", "चैटजीपीटी", "चैट जीपीटी"],
    exact: [],
  },
  {
    key: "openai",
    name: "OpenAI",
    slug: null,
    hex: "000000",
    logo: true,
    words: ["openai", "open ai"],
    exact: [],
  },
  {
    key: "perplexity",
    name: "Perplexity",
    slug: "perplexity",
    hex: "1FB8CD",
    logo: true,
    words: ["perplexity ai"],
    exact: [],
  },
  {
    key: "excel",
    name: "Microsoft Excel",
    slug: null,
    hex: "217346",
    words: ["excel sheet", "ms excel", "microsoft excel", "एक्सेल"],
    exact: ["Excel"],
  },
  {
    key: "powerpoint",
    name: "PowerPoint",
    slug: null,
    hex: "B7472A",
    words: ["powerpoint", "power point", "पीपीटी"],
    exact: ["PPT"],
  },
  {
    key: "microsoft",
    name: "Microsoft",
    slug: null,
    hex: "5E5E5E",
    logo: true,
    words: ["microsoft", "माइक्रोसॉफ्ट"],
    exact: [],
  },
  {
    key: "notion",
    name: "Notion",
    slug: "notion",
    hex: "000000",
    logo: true,
    words: [],
    exact: ["Notion"],
  },
  {
    key: "slack",
    name: "Slack",
    slug: null,
    hex: "4A154B",
    logo: true,
    words: [],
    exact: ["Slack"],
  },
  {
    key: "trello",
    name: "Trello",
    slug: "trello",
    hex: "0052CC",
    logo: true,
    words: ["trello"],
    exact: [],
  },
  {
    key: "asana",
    name: "Asana",
    slug: "asana",
    hex: "F06A6A",
    logo: true,
    words: [],
    exact: ["Asana"],
  },
  {
    key: "clickup",
    name: "ClickUp",
    slug: "clickup",
    hex: "7B68EE",
    logo: true,
    words: ["clickup", "click up"],
    exact: [],
  },
  {
    key: "airtable",
    name: "Airtable",
    slug: "airtable",
    hex: "18BFFF",
    logo: true,
    words: ["airtable"],
    exact: [],
  },
  {
    key: "figma",
    name: "Figma",
    slug: "figma",
    hex: "F24E1E",
    logo: true,
    words: ["figma"],
    exact: [],
  },
  {
    key: "canva",
    name: "Canva",
    slug: null,
    hex: "00C4CC",
    logo: true,
    words: ["canva", "कैनवा"],
    exact: [],
  },
  {
    key: "calendly",
    name: "Calendly",
    slug: "calendly",
    hex: "006BFF",
    words: ["calendly"],
    exact: [],
  },
  {
    key: "typeform",
    name: "Typeform",
    slug: "typeform",
    hex: "262627",
    logo: true,
    words: ["typeform"],
    exact: [],
  },
  {
    key: "mailchimp",
    name: "Mailchimp",
    slug: "mailchimp",
    hex: "FFE01B",
    logo: true,
    words: ["mailchimp"],
    exact: [],
  },
  {
    key: "hubspot",
    name: "HubSpot",
    slug: "hubspot",
    hex: "FF7A59",
    logo: true,
    words: ["hubspot", "हबस्पॉट"],
    exact: [],
  },
  {
    key: "salesforce",
    name: "Salesforce",
    slug: null,
    hex: "00A1E0",
    logo: true,
    words: ["salesforce"],
    exact: [],
  },
  {
    key: "zoho",
    name: "Zoho",
    slug: "zoho",
    hex: "E42527",
    words: ["zoho", "ज़ोहो", "जोहो"],
    exact: [],
  },
  {
    key: "pipedrive",
    name: "Pipedrive",
    slug: null,
    hex: "017737",
    words: ["pipedrive"],
    exact: [],
  },
  {
    key: "freshworks",
    name: "Freshworks",
    slug: null,
    hex: "FF6600",
    words: ["freshworks", "freshdesk", "freshsales"],
    exact: [],
  },
  {
    key: "tally",
    name: "Tally",
    slug: null,
    hex: "1B6DC1",
    words: ["tally erp", "tallyprime", "tally prime", "टैली"],
    exact: ["Tally"],
  },
  {
    key: "wordpress",
    name: "WordPress",
    slug: "wordpress",
    hex: "21759B",
    logo: true,
    words: ["wordpress", "वर्डप्रेस"],
    exact: [],
  },
  {
    key: "wix",
    name: "Wix",
    slug: "wix",
    hex: "0C6EFC",
    logo: true,
    words: ["wix.com"],
    exact: ["Wix"],
  },
  {
    key: "shopify",
    name: "Shopify",
    slug: "shopify",
    hex: "7AB55C",
    logo: true,
    words: ["shopify", "शॉपिफाई"],
    exact: [],
  },
  {
    key: "godaddy",
    name: "GoDaddy",
    slug: "godaddy",
    hex: "1BDBDB",
    words: ["godaddy", "go daddy"],
    exact: [],
  },
  {
    key: "zapier",
    name: "Zapier",
    slug: "zapier",
    hex: "FF4F00",
    logo: true,
    words: ["zapier"],
    exact: [],
  },
  {
    key: "linktree",
    name: "Linktree",
    slug: "linktree",
    hex: "43E55E",
    words: ["linktree", "link tree"],
    exact: [],
  },
  {
    key: "kajabi",
    name: "Kajabi",
    slug: null,
    hex: "2E91FC",
    words: ["kajabi"],
    exact: [],
  },
  {
    key: "teachable",
    name: "Teachable",
    slug: null,
    hex: "000000",
    words: ["teachable"],
    exact: [],
  },
  {
    key: "instamojo",
    name: "Instamojo",
    slug: null,
    hex: "2E2E2E",
    words: ["instamojo", "इंस्टामोजो"],
    exact: [],
  },
  {
    key: "razorpay",
    name: "Razorpay",
    slug: "razorpay",
    hex: "0C2451",
    words: ["razorpay", "रेज़रपे", "रेजरपे"],
    exact: [],
  },
  {
    key: "paytm",
    name: "Paytm",
    slug: "paytm",
    hex: "20336B",
    words: ["paytm", "पेटीएम"],
    exact: [],
  },
  {
    key: "phonepe",
    name: "PhonePe",
    slug: "phonepe",
    hex: "5F259F",
    words: ["phonepe", "phone pe", "फोनपे", "फ़ोनपे", "फोन पे"],
    exact: [],
  },
  {
    key: "upi",
    name: "UPI",
    slug: null,
    hex: "097939",
    words: ["upi", "यूपीआई"],
    exact: [],
  },
  {
    key: "paypal",
    name: "PayPal",
    slug: "paypal",
    hex: "002991",
    logo: true,
    words: ["paypal", "pay pal"],
    exact: [],
  },
  {
    key: "stripe",
    name: "Stripe",
    slug: "stripe",
    hex: "635BFF",
    logo: true,
    words: [],
    exact: ["Stripe"],
  },
  {
    key: "mastercard",
    name: "Mastercard",
    slug: "mastercard",
    hex: "EB001B",
    logo: true,
    words: ["mastercard", "master card"],
    exact: [],
  },
  {
    key: "visa",
    name: "Visa",
    slug: "visa",
    hex: "1A1F71",
    logo: true,
    words: ["visa card"],
    exact: ["VISA"],
  },
  {
    key: "amazon",
    name: "Amazon",
    slug: null,
    hex: "FF9900",
    logo: true,
    words: ["amazon", "अमेज़न", "अमेज़ॉन", "अमेजन", "अमेजॉन"],
    exact: [],
  },
  {
    key: "primevideo",
    name: "Prime Video",
    slug: null,
    hex: "1F2E3E",
    words: ["prime video", "amazon prime"],
    exact: [],
  },
  {
    key: "flipkart",
    name: "Flipkart",
    slug: null,
    hex: "2874F0",
    words: ["flipkart", "फ्लिपकार्ट"],
    exact: [],
  },
  {
    key: "meesho",
    name: "Meesho",
    slug: null,
    hex: "F43397",
    words: ["meesho", "मीशो"],
    exact: [],
  },
  {
    key: "myntra",
    name: "Myntra",
    slug: null,
    hex: "FF3F6C",
    words: ["myntra", "मिंत्रा"],
    exact: [],
  },
  {
    key: "nykaa",
    name: "Nykaa",
    slug: null,
    hex: "FC2779",
    words: ["nykaa", "नायका"],
    exact: [],
  },
  {
    key: "swiggy",
    name: "Swiggy",
    slug: "swiggy",
    hex: "FC8019",
    words: ["swiggy", "स्विगी"],
    exact: [],
  },
  {
    key: "zomato",
    name: "Zomato",
    slug: "zomato",
    hex: "E23744",
    words: ["zomato", "ज़ोमैटो", "जोमैटो"],
    exact: [],
  },
  {
    key: "zepto",
    name: "Zepto",
    slug: null,
    hex: "5E17EB",
    words: ["zepto"],
    exact: [],
  },
  {
    key: "blinkit",
    name: "Blinkit",
    slug: null,
    hex: "F8CB46",
    words: ["blinkit"],
    exact: [],
  },
  {
    key: "bigbasket",
    name: "BigBasket",
    slug: "bigbasket",
    hex: "A5CD39",
    words: ["bigbasket", "big basket"],
    exact: [],
  },
  {
    key: "indiamart",
    name: "IndiaMART",
    slug: null,
    hex: "2E3192",
    words: ["indiamart", "india mart", "इंडियामार्ट"],
    exact: [],
  },
  {
    key: "justdial",
    name: "Justdial",
    slug: null,
    hex: "FF6C00",
    words: ["justdial", "just dial", "जस्टडायल"],
    exact: [],
  },
  {
    key: "naukri",
    name: "Naukri.com",
    slug: null,
    hex: "4A90E2",
    words: ["naukri.com"],
    exact: [],
  },
  {
    key: "olx",
    name: "OLX",
    slug: null,
    hex: "002F34",
    words: ["olx"],
    exact: [],
  },
  {
    key: "airbnb",
    name: "Airbnb",
    slug: "airbnb",
    hex: "FF5A5F",
    logo: true,
    words: ["airbnb"],
    exact: [],
  },
  {
    key: "oyo",
    name: "OYO",
    slug: "oyo",
    hex: "EE2E24",
    words: [],
    exact: ["OYO", "Oyo"],
  },
  {
    key: "makemytrip",
    name: "MakeMyTrip",
    slug: null,
    hex: "E42F29",
    words: ["makemytrip", "make my trip"],
    exact: [],
  },
  {
    key: "uber",
    name: "Uber",
    slug: "uber",
    hex: "000000",
    logo: true,
    words: ["uber", "उबर"],
    exact: [],
  },
  {
    key: "ola",
    name: "Ola",
    slug: null,
    hex: "000000",
    words: [],
    exact: ["Ola"],
  },
  {
    key: "rapido",
    name: "Rapido",
    slug: null,
    hex: "FFD700",
    words: ["rapido"],
    exact: [],
  },
  {
    key: "netflix",
    name: "Netflix",
    slug: "netflix",
    hex: "E50914",
    logo: true,
    words: ["netflix", "नेटफ्लिक्स"],
    exact: [],
  },
  {
    key: "hotstar",
    name: "JioHotstar",
    slug: null,
    hex: "1F80E0",
    words: ["hotstar", "jiohotstar"],
    exact: [],
  },
  {
    key: "spotify",
    name: "Spotify",
    slug: "spotify",
    hex: "1ED760",
    logo: true,
    words: ["spotify"],
    exact: [],
  },
  {
    key: "jio",
    name: "Jio",
    slug: "jio",
    hex: "0A2885",
    words: [],
    exact: ["Jio", "JIO"],
  },
  {
    key: "airtel",
    name: "Airtel",
    slug: "airtel",
    hex: "E40000",
    words: ["airtel", "एयरटेल"],
    exact: [],
  },
  {
    key: "tata",
    name: "Tata",
    slug: "tata",
    hex: "486AAE",
    words: [],
    exact: ["Tata", "TATA"],
  },
  {
    key: "hdfc",
    name: "HDFC Bank",
    slug: "hdfcbank",
    hex: "004B8D",
    words: ["hdfc", "एचडीएफसी"],
    exact: [],
  },
  {
    key: "icici",
    name: "ICICI Bank",
    slug: null,
    hex: "AE282E",
    words: ["icici", "आईसीआईसीआई"],
    exact: [],
  },
  {
    key: "sbi",
    name: "SBI",
    slug: null,
    hex: "22409A",
    words: ["state bank of india"],
    exact: ["SBI"],
  },
  {
    key: "kotak",
    name: "Kotak",
    slug: null,
    hex: "ED1C24",
    words: ["kotak", "कोटक"],
    exact: [],
  },
  {
    key: "axis",
    name: "Axis Bank",
    slug: "axisbank",
    hex: "971A4D",
    words: ["axis bank"],
    exact: [],
  },
  {
    key: "zerodha",
    name: "Zerodha",
    slug: "zerodha",
    hex: "387ED1",
    words: ["zerodha", "ज़ेरोधा", "जेरोधा"],
    exact: [],
  },
  {
    key: "groww",
    name: "Groww",
    slug: null,
    hex: "00D09C",
    words: ["groww"],
    exact: [],
  },
  {
    key: "upstox",
    name: "Upstox",
    slug: null,
    hex: "5A298B",
    words: ["upstox"],
    exact: [],
  },
  {
    key: "angelone",
    name: "Angel One",
    slug: null,
    hex: "1F3B73",
    words: ["angel one"],
    exact: [],
  },
  {
    key: "cred",
    name: "CRED",
    slug: null,
    hex: "000000",
    words: [],
    exact: ["CRED"],
  },
  {
    key: "bharatpe",
    name: "BharatPe",
    slug: null,
    hex: "00BAA0",
    words: ["bharatpe", "bharat pe"],
    exact: [],
  },
  {
    key: "byjus",
    name: "BYJU'S",
    slug: "byjus",
    hex: "813588",
    words: ["byju's", "byjus", "बायजूस"],
    exact: [],
  },
  {
    key: "unacademy",
    name: "Unacademy",
    slug: "unacademy",
    hex: "08BD80",
    words: ["unacademy"],
    exact: [],
  },
  {
    key: "udemy",
    name: "Udemy",
    slug: "udemy",
    hex: "A435F0",
    logo: true,
    words: ["udemy"],
    exact: [],
  },
  {
    key: "coursera",
    name: "Coursera",
    slug: "coursera",
    hex: "0056D2",
    logo: true,
    words: ["coursera"],
    exact: [],
  },
  {
    key: "apple",
    name: "Apple",
    slug: "apple",
    hex: "000000",
    logo: true,
    words: ["iphone", "आईफोन", "macbook"],
    exact: ["Apple", "iPad"],
  },
  {
    key: "android",
    name: "Android",
    slug: null,
    hex: "34A853",
    logo: true,
    words: ["android", "एंड्रॉइड", "एंड्रॉयड"],
    exact: [],
  },
  {
    key: "samsung",
    name: "Samsung",
    slug: "samsung",
    hex: "1428A0",
    logo: true,
    words: ["samsung", "सैमसंग"],
    exact: [],
  },
  {
    key: "github",
    name: "GitHub",
    slug: "github",
    hex: "181717",
    logo: true,
    words: ["github"],
    exact: [],
  },
  {
    key: "chrome",
    name: "Google Chrome",
    slug: "googlechrome",
    hex: "4285F4",
    logo: true,
    words: ["google chrome"],
    exact: ["Chrome"],
  },
  {
    key: "appstore",
    name: "App Store",
    slug: "appstore",
    hex: "0D96F6",
    logo: true,
    words: ["app store", "appstore"],
    exact: [],
  },
];
