import type { Coaching } from "./coaching-client";

/** Invented contract fixture. Never a substitute for a real learner's history. */
export const fictionalCoaching: Coaching & {
  entitlement_policy: string;
  recommended_media: null;
  other_format: null;
} = {
  schema: "ac.sales-xray.coaching/1",
  person_id: "00000000-0000-0000-0000-000000000001",
  tenant_id: "00000000-0000-0000-0000-000000000002",
  authority: "provisional",
  entitlement: "coaching",
  entitlement_policy: "AUT-1678-open-access",
  state: "ready",
  analysed_calls: 2,
  pending_calls: 0,
  unavailable_calls: 0,
  history_limited: false,
  focus: {
    skill_id: "problem_impact_desire",
    label: "Problem, Impact & Desire Clarity",
    explanation: "Explore the consequence before recommending a solution.",
    why_it_matters: "The recommendation needs a clear purpose.",
    selected_reason: "Two comparable calls include suggestions for this skill.",
    selected_at: "2026-10-09T10:00:00Z",
    status: "active",
    verdict: "Ask one impact question.",
  },
  pattern: {
    relevant_call_count: 2,
    attention_call_count: 2,
    summary: "Compare the situations in two calls.",
  },
  root_cause: {
    hypothesis: "We do not yet have enough evidence to say why.",
    gap_type: "uncertain",
    confidence: "uncertain",
  },
  evidence: [1, 2].map((index) => ({
    submission_id: `00000000-0000-0000-0000-00000000001${index}`,
    recording_id: `00000000-0000-0000-0000-00000000002${index}`,
    source_sha256: "a".repeat(64),
    transcript_revision: "fictional-v1",
    created_at: "2026-10-09T10:00:00Z",
    call_label: `Fictional call ${index}`,
    segment_id: "segment-1",
    quote: "हैंडओवर में समय लगता है. कामाला वेळ लागतो.",
    start_ms: 1000,
    end_ms: 4000,
    observation: "The handover consequence remained unclear.",
    playable: true,
  })),
  practice: {
    exercise: "Say one follow-up in your own words.",
    success_condition: "The question explores a consequence.",
    gap_type: "uncertain",
    estimated_minutes: null,
  },
  mission: {
    skill_id: "problem_impact_desire",
    behavior: "Ask one impact question.",
    context: "When a meaningful problem's impact is unclear.",
    done_when: "One relevant consequence is explored.",
    cue: "Understand the impact before choosing a solution.",
    active_since: "2026-10-09T10:00:00Z",
    origin_submission_id: "00000000-0000-0000-0000-000000000011",
    status: "active",
  },
  mastery: {
    state: "not_enough_evidence",
    trend: "not_enough_evidence",
    relevant_count: null,
    correct_count: null,
    baseline: null,
    confidence: "uncertain",
    historical_achievement: null,
    explanation: "Call observations cannot establish mastery.",
  },
  regression: {
    state: "unknown",
    action: "More comparable behavior evidence is needed.",
  },
  lesson: null,
  recommended_media: null,
  other_format: null,
  development_path: {
    current: "Problem, Impact & Desire Clarity",
    likely_next: null,
    maintain: null,
    later: null,
    explanation: "Future evidence guides your path.",
  },
  reflection_question: "What influenced your response in this moment?",
  feedback_available: false,
  limitations: [
    "Coaching is provisional.",
    "Saving learner context is not available yet.",
  ],
};
fictionalCoaching.lesson = {
  title: "Understand the impact before choosing a solution",
  quick_idea: "Explore what the problem is causing.",
  framework: ["Problem", "Impact", "Desired outcome", "Relevant solution"],
  why_it_matters: "Connect the recommendation to the situation.",
  good_looks_like: "Explore one relevant consequence.",
  better_direction: "Ask one impact question.",
  example_wording: ["What does that affect in your work?"],
  when_to_use: "When impact is unclear.",
  when_not: "Stop when the point is already clear.",
  checklist: ["Problem clear?", "Impact clear?", "Outcome clear?"],
  source: "Owner's binding Coaching specification",
  own_call: fictionalCoaching.evidence[0],
  next_call_connection: "Ask one impact question.",
};
