DatabaseOwner clamav
DatabaseDirectory /var/lib/clamav
DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
ScriptedUpdates yes
TestDatabases yes
NotifyClamd /etc/clamav/clamd.conf
Checks 12
ConnectTimeout 20
ReceiveTimeout 60
MaxAttempts 3
LogTime yes
LogVerbose no
