"""Replaceable provider ports, fake adapters, and webhook inbox dedupe."""

from ac_platform.providers.email import (
    create_email_provider,
    create_email_provider_from_settings,
    email_provider_factory,
    get_email_provider,
)
from ac_platform.providers.fake_email import FakeEmailAdapter, FakeEmailProvider
from ac_platform.providers.models import ProviderInbox, ProviderInboxStatus
from ac_platform.providers.ports import (
    AmbiguousDeliveryProviderError,
    ApprovedTemplateRegistry,
    DeliveryReceipt,
    EmailCommunication,
    EmailMessage,
    EmailMessageConflictError,
    EmailProvider,
    PermanentProviderError,
    ProviderError,
    SentEmail,
    TransientProviderError,
)
from ac_platform.providers.resend_email import ResendEmailAdapter
from ac_platform.providers.service import (
    ConfiguredWebhookAdapter,
    DuplicateProviderEvent,
    HmacWebhookVerifier,
    ProviderInboxRepository,
    ProviderPayloadConflict,
    ProviderWebhookRejected,
    TrustedWebhookAdapter,
    WebhookAttribution,
    build_provider_inbox_acknowledge_statement,
    build_provider_inbox_claim_statement,
    build_provider_inbox_exhausted_statement,
    build_provider_inbox_failure_statement,
    build_provider_inbox_insert_statement,
    build_provider_inbox_renew_statement,
    build_provider_inbox_take_statement,
    deterministic_provider_retry_delay,
)

__all__ = [
    "AmbiguousDeliveryProviderError",
    "ApprovedTemplateRegistry",
    "DeliveryReceipt",
    "DuplicateProviderEvent",
    "EmailCommunication",
    "EmailMessage",
    "EmailMessageConflictError",
    "EmailProvider",
    "FakeEmailAdapter",
    "FakeEmailProvider",
    "HmacWebhookVerifier",
    "ConfiguredWebhookAdapter",
    "PermanentProviderError",
    "ProviderError",
    "ProviderInbox",
    "ProviderInboxRepository",
    "ProviderPayloadConflict",
    "ProviderInboxStatus",
    "ProviderWebhookRejected",
    "ResendEmailAdapter",
    "TrustedWebhookAdapter",
    "WebhookAttribution",
    "SentEmail",
    "TransientProviderError",
    "build_provider_inbox_acknowledge_statement",
    "build_provider_inbox_claim_statement",
    "build_provider_inbox_exhausted_statement",
    "build_provider_inbox_failure_statement",
    "build_provider_inbox_insert_statement",
    "build_provider_inbox_renew_statement",
    "build_provider_inbox_take_statement",
    "create_email_provider",
    "create_email_provider_from_settings",
    "email_provider_factory",
    "deterministic_provider_retry_delay",
    "get_email_provider",
]
