"""Fixed child-only authentication for the hosted Sales Xray provider broker.

The coordinator starts this module with a sterile environment and one
non-secret reference in :data:`CHILD_TOKEN_FILE_ENV`.  This module opens that
externally managed file inside the child, accepts only one Infisical token, and
then replaces itself with the fixed Infisical command generated by
``InfisicalLauncher``.  No coordinator setting, provider key, request value,
endpoint or user command is accepted from the request frame.

The token file is intentionally not read by the coordinator and its reference
is intentionally absent from argv.  Errors are returned as the broker's
content-free response frame, never as exception text or child stderr.
"""

from __future__ import annotations

import os
import re
import stat
import sys
from collections.abc import Sequence
from contextlib import suppress
from pathlib import Path
from typing import Any

from ac_platform.conversation_intelligence.inference_broker import (
    _RUNTIME_ENV_NAMES,
    CHILD_TOKEN_FILE_ENV,
    INFISICAL_API_URL,
    InferenceBrokerError,
    InfisicalLauncher,
    _child_response_error,
    _secret_file_reference,
)

_TOKEN_ENV = "INFISICAL_TOKEN"  # noqa: S105 - environment name only
_TOKEN_FILE_MAX_BYTES = 4096
_TOKEN = re.compile(r"^[A-Za-z0-9._~+/=-]{16,4096}$")
_IDENTITY_ARGUMENTS = (
    "--infisical-executable",
    "--project-id",
    "--environment",
    "--path",
)


def _read_token_file(reference: object) -> str:
    """Read exactly one token from a child-readable, regular secret file."""

    try:
        path_reference = _secret_file_reference(reference)
        path = Path(path_reference)
    except (TypeError, ValueError):
        raise InferenceBrokerError("broker_service_identity_file_invalid") from None

    file_descriptor: int | None = None
    try:
        if path.is_symlink():
            raise InferenceBrokerError("broker_service_identity_file_invalid")
        flags = os.O_RDONLY
        if os.name == "posix":
            flags |= getattr(os, "O_NOFOLLOW", 0)
        file_descriptor = os.open(path, flags)
        information = os.fstat(file_descriptor)
        if not stat.S_ISREG(information.st_mode) or not 0 < information.st_size <= (
            _TOKEN_FILE_MAX_BYTES
        ):
            raise InferenceBrokerError("broker_service_identity_file_invalid")
        if os.name == "posix" and stat.S_IMODE(information.st_mode) not in {0o400, 0o600}:
            raise InferenceBrokerError("broker_service_identity_file_invalid")
        raw = os.read(file_descriptor, _TOKEN_FILE_MAX_BYTES + 1)
    except InferenceBrokerError:
        raise
    except (OSError, ValueError):
        raise InferenceBrokerError("broker_service_identity_unavailable") from None
    finally:
        if file_descriptor is not None:
            with suppress(OSError):
                os.close(file_descriptor)

    if len(raw) > _TOKEN_FILE_MAX_BYTES:
        raise InferenceBrokerError("broker_service_identity_file_invalid")
    try:
        value = raw.decode("ascii")
    except UnicodeDecodeError:
        raise InferenceBrokerError("broker_service_identity_file_invalid") from None

    # A deployment may materialize either a raw one-line token or the one
    # explicitly named environment assignment.  Any second key/value or
    # whitespace-bearing format is rejected so a coordinator/API env file can
    # never be treated as a service identity file.
    if value.endswith("\n"):
        value = value[:-1]
        if value.endswith("\r"):
            value = value[:-1]
    if value.startswith(f"{_TOKEN_ENV}="):
        value = value[len(_TOKEN_ENV) + 1 :]
    if not _TOKEN.fullmatch(value):
        raise InferenceBrokerError("broker_service_identity_file_invalid")
    return value


def _parse_argv(argv: Sequence[str]) -> tuple[str, str, str, str]:
    """Parse the exact launcher shape; no endpoint or command is configurable."""

    if len(argv) != 1 + len(_IDENTITY_ARGUMENTS) * 2 or argv[0] != "--child":
        raise InferenceBrokerError("broker_service_identity_file_invalid")
    values: list[str] = []
    for index, name in enumerate(_IDENTITY_ARGUMENTS):
        option_index = 1 + index * 2
        if argv[option_index] != name or not isinstance(argv[option_index + 1], str):
            raise InferenceBrokerError("broker_service_identity_file_invalid")
        values.append(argv[option_index + 1])
    return tuple(values)  # type: ignore[return-value]


def _identity_environment(token: str) -> dict[str, str]:
    """Build a sterile Infisical environment with only the fixed service token."""

    environment = {
        name: value
        for name in _RUNTIME_ENV_NAMES
        if (value := os.environ.get(name))
    }
    environment.pop(CHILD_TOKEN_FILE_ENV, None)
    environment.pop(_TOKEN_ENV, None)
    environment["INFISICAL_API_URL"] = INFISICAL_API_URL
    environment["INFISICAL_DISABLE_UPDATE_CHECK"] = "true"
    environment[_TOKEN_ENV] = token
    return environment


def _write_error(code: str) -> int:
    """Write one content-free broker frame and no diagnostic text."""

    frame = _child_response_error(code)
    stream: Any = getattr(sys.stdout, "buffer", sys.stdout)
    stream.write(frame)
    stream.flush()
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    """Authenticate one fixed provider child, then replace this process."""

    token: str | None = None
    try:
        command = _parse_argv(tuple(sys.argv[1:] if argv is None else argv))
        executable, project, environment, secret_path = command
        token = _read_token_file(os.environ.get(CHILD_TOKEN_FILE_ENV))
        # The provider is encoded by the final path component and is checked
        # again by InfisicalLauncher before constructing the direct command.
        provider = secret_path.rstrip("/").split("/")[-1]
        launcher = InfisicalLauncher(
            executable=executable,
            provider_id=provider,
            project_ref=project,
            environment_ref=environment,
            secret_path_ref=secret_path,
            token_file_ref=os.environ.get(CHILD_TOKEN_FILE_ENV),
        )
        child_environment = _identity_environment(token)
        os.environ.clear()
        os.environ.update(child_environment)
        # The token is supplied through the child environment to Infisical.
        # os.execvpe replaces this process; no Python coordinator continues
        # with the token in scope after the provider child is admitted.
        os.execvpe(  # noqa: S606 - executable and argv are fixed by InfisicalLauncher
            str(launcher.executable),
            launcher.provider_argv(sys.executable),
            child_environment,
        )
    except InferenceBrokerError as error:
        return _write_error(error.code)
    except (OSError, TypeError, ValueError, KeyError):
        return _write_error("broker_service_identity_unavailable")
    except Exception:
        return _write_error("broker_child_failed")
    finally:
        # execvpe does not return on success.  On an error, remove the service
        # token from the disposable child environment before returning.
        if token is not None:
            os.environ.pop(_TOKEN_ENV, None)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["main"]
