export const ROUTES = {
  home: "/",
  privacy: "/privacy",
  terms: "/terms",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  verifyEmail: "/verify-email",
  resetPassword: "/reset-password",
  callback: "/auth/callback",
  sessionExpired: "/session-expired",
  onboarding: "/onboarding",
  learnerHome: "/home",
  myLearning: "/home#my-learning",
  practice: "/home#practice",
  progress: "/progress",
  settings: "/settings",
  programDetail: (slug: string) => `/programs/${slug}`,
  programLearning: (slug: string) => `/learn/${slug}`,
  module: (slug: string, moduleId: string) =>
    `/learn/${slug}/module/${moduleId}`,
  activity: (activityId: string) => `/activity/${activityId}`,
  completion: (slug: string) => `/learn/${slug}/complete`,
  certificate: (certificateId: string) => `/certificates/${certificateId}`,
} as const;
