"""Provider-neutral media delivery contract foundation."""

from ac_platform.media.contracts import (
    AuthorizedMediaVersion,
    CaptionTrackDescriptor,
    EphemeralMediaUrl,
    MediaAssetId,
    MediaAssetVersion,
    MediaAuthorizationContext,
    MediaDeliveryDescriptor,
    MediaDeliveryKind,
    MediaDeliveryMetadata,
    MediaDeliveryPort,
    MediaVersionId,
    PlaybackGrantDescriptor,
    PosterDescriptor,
    RenditionDescriptor,
    TranscriptDescriptor,
    TranscriptFormat,
    create_media_authorization_context,
    resolve_authorized_delivery,
)
from ac_platform.media.errors import (
    MediaAuthorizationMismatchError,
    MediaDeliveryError,
    MediaExpiredError,
    MediaNotYetValidError,
    MediaOriginError,
    MediaPolicyDeniedError,
    MediaProcessingError,
    MediaRangeError,
    MediaUnavailableError,
    MediaUnsupportedError,
)

__all__ = [
    "AuthorizedMediaVersion",
    "CaptionTrackDescriptor",
    "MediaAuthorizationContext",
    "MediaAuthorizationMismatchError",
    "EphemeralMediaUrl",
    "MediaAssetId",
    "MediaAssetVersion",
    "MediaDeliveryDescriptor",
    "MediaDeliveryError",
    "MediaDeliveryKind",
    "MediaDeliveryMetadata",
    "MediaDeliveryPort",
    "MediaExpiredError",
    "MediaNotYetValidError",
    "MediaOriginError",
    "MediaPolicyDeniedError",
    "MediaProcessingError",
    "MediaRangeError",
    "MediaUnsupportedError",
    "MediaUnavailableError",
    "MediaVersionId",
    "PlaybackGrantDescriptor",
    "PosterDescriptor",
    "RenditionDescriptor",
    "TranscriptDescriptor",
    "TranscriptFormat",
    "create_media_authorization_context",
    "resolve_authorized_delivery",
]
