"""Fail-closed composition for non-production media stress fixtures.

The acquisition/rendering tools live under ``tools/media-player-stress``
because fixture bytes are test inputs, not product content.  This module is
the application-facing seam: it loads the one approved registry, rechecks the
cached bytes and ffprobe metadata, and then requires typed provider/grant
verifiers before returning a local source descriptor.  It never accepts a
caller-supplied URL or media metadata and never creates provider state or a
playback grant.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
import shutil
import stat
import subprocess
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from ac_platform.media.contracts import (
    MediaAuthorizationContext,
    PlaybackGrantDescriptor,
)
from ac_platform.media.errors import MediaConfigurationError

_SHA256 = re.compile(r"^[0-9a-fA-F]{64}$")
_FIXTURE_ID = re.compile(r"^[a-z0-9][a-z0-9-]{1,79}$")
_FPS = re.compile(r"^[1-9][0-9]{0,4}/[1-9][0-9]{0,4}$")
_ALLOWED_ENVIRONMENTS = frozenset({"test", "development", "staging"})
_ALLOWED_CONTENT_TYPES = frozenset({"video/mp4", "video/webm"})
_ALLOWED_VIDEO_CODECS = frozenset({"h264"})
_ALLOWED_AUDIO_CODECS = frozenset({"aac", "mp3", "ac3"})
_MAX_FIXTURE_BYTES = 8 * 1024 * 1024 * 1024
_MAX_MANIFEST_BYTES = 2 * 1024 * 1024
_MAX_PROBE_BYTES = 2 * 1024 * 1024
_SOURCE_URLS = frozenset(
    {
        "https://download.blender.org/demo/movies/BBB/bbb_sunflower_2160p_30fps_normal.mp4.zip",
        "https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4.zip",
        "https://download.blender.org/demo/movies/caminandes_gran_dillama.mp4.zip",
    }
)
_SOURCE_PAGE_URLS = frozenset(
    {"https://peach.blender.org/about/", "https://studio.blender.org/projects/api/assets/2363/"}
)
_SOURCE_INDEX_URLS = frozenset(
    {
        "https://download.blender.org/demo/movies/BBB/",
        "https://peach.blender.org/download/",
        "https://download.blender.org/demo/movies/",
    }
)
_LICENSE_URLS = frozenset(
    {"https://creativecommons.org/licenses/by/3.0/", "https://creativecommons.org/licenses/by/4.0/"}
)
_EXPECTED_ARCHIVE_MEMBERS = {
    (
        "https://download.blender.org/demo/movies/BBB/bbb_sunflower_2160p_30fps_normal.mp4.zip"
    ): "bbb_sunflower_2160p_30fps_normal.mp4",
    (
        "https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4.zip"
    ): "BigBuckBunny_320x180.mp4",
    (
        "https://download.blender.org/demo/movies/caminandes_gran_dillama.mp4.zip"
    ): "caminandes_gran_dillama.mp4",
}
_EXPECTED_EXTERNAL_PROVENANCE = {
    ("https://download.blender.org/demo/movies/BBB/bbb_sunflower_2160p_30fps_normal.mp4.zip"): {
        "license": "Creative Commons Attribution 3.0",
        "license_url": "https://creativecommons.org/licenses/by/3.0/",
        "source_page": "https://peach.blender.org/about/",
        "source_index": "https://download.blender.org/demo/movies/BBB/",
        "source_index_date": "2023-11-24",
        "attribution": (
            "Blender Foundation 2008, Janus Bager Kristensen 2013; "
            "Big Buck Bunny, Sunflower version"
        ),
    },
    ("https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4.zip"): {
        "license": "Creative Commons Attribution 3.0",
        "license_url": "https://creativecommons.org/licenses/by/3.0/",
        "source_page": "https://peach.blender.org/about/",
        "source_index": "https://peach.blender.org/download/",
        "source_index_date": "2008-06-05",
        "attribution": "Blender Foundation; Big Buck Bunny",
    },
    ("https://download.blender.org/demo/movies/caminandes_gran_dillama.mp4.zip"): {
        "license": "Creative Commons Attribution 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "source_page": "https://studio.blender.org/projects/api/assets/2363/",
        "source_index": "https://download.blender.org/demo/movies/",
        "source_index_date": "2023-11-24",
        "attribution": (
            "Blender Foundation / Blender Studio; Caminandes 2: Gran Dillama (2013), "
            "directed by Pablo Vazquez; studio.blender.org"
        ),
    },
}
_EXPECTED_GENERATED_LICENSE = "No third-party content; generated by the FFmpeg test source"
_EXPECTED_GENERATED_ATTRIBUTION = "FFmpeg testsrc2 filter"
_EXPECTED_GENERATED_FFMPEG_ARGS = {
    "generated-16x9-4s": (
        "-nostdin",
        "-hide_banner",
        "-loglevel",
        "error",
        "-f",
        "lavfi",
        "-i",
        "testsrc2=size=320x180:rate=30",
        "-t",
        "4",
        "-an",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
    ),
    "generated-4x3-6s": (
        "-nostdin",
        "-hide_banner",
        "-loglevel",
        "error",
        "-f",
        "lavfi",
        "-i",
        "testsrc2=size=320x240:rate=30",
        "-t",
        "6",
        "-an",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
    ),
    "generated-wide-3s": (
        "-nostdin",
        "-hide_banner",
        "-loglevel",
        "error",
        "-f",
        "lavfi",
        "-i",
        "testsrc2=size=640x272:rate=30",
        "-t",
        "3",
        "-an",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
    ),
}
_COMMON_FIXTURE_FIELDS = frozenset(
    {
        "id",
        "title",
        "kind",
        "course_content",
        "cache_path",
        "sha256",
        "content_type",
        "license",
        "license_url",
        "attribution",
        "metadata",
    }
)
_EXTERNAL_FIXTURE_FIELDS = _COMMON_FIXTURE_FIELDS | frozenset(
    {
        "source_url",
        "source_page",
        "source_index",
        "source_index_date",
        "source_date_basis",
        "retrieved_at",
        "archive_cache_path",
        "archive_member",
        "archive_sha256",
    }
)
_GENERATED_FIXTURE_FIELDS = _COMMON_FIXTURE_FIELDS | frozenset({"ffmpeg_args"})
_EXPECTED_FIXTURE_MANIFEST_SHA256 = (
    "fc61c87d5428d53d35b82061a53fbdbd9967b8bf658c6d0425a78a07bc106290"
)
_EXPECTED_CACHE_PATHS = {
    "bbb-4k-30-normal": "sources/bbb-4k-30-normal/bbb_sunflower_2160p_30fps_normal.mp4",
    "bbb-320x180-24": "sources/bbb-320x180-24/BigBuckBunny_320x180.mp4",
    "caminandes-gran-dillama-1080p": (
        "sources/caminandes-gran-dillama-1080p/caminandes_gran_dillama.mp4"
    ),
    "generated-16x9-4s": "generated/generated-16x9-4s.mp4",
    "generated-4x3-6s": "generated/generated-4x3-6s.mp4",
    "generated-wide-3s": "generated/generated-wide-3s.mp4",
}
_EXPECTED_ARCHIVE_CACHE_PATHS = {
    "bbb-4k-30-normal": ("sources/bbb-4k-30-normal/bbb_sunflower_2160p_30fps_normal.mp4.zip"),
    "bbb-320x180-24": "sources/bbb-320x180-24/BigBuckBunny_320x180.mp4.zip",
    "caminandes-gran-dillama-1080p": (
        "sources/caminandes-gran-dillama-1080p/caminandes_gran_dillama.mp4.zip"
    ),
}

# These paths are intentionally derived from this checked-out repository, not
# from a caller or a deployment-provided URL.  The path is exact so production
# code cannot point this seam at an arbitrary manifest.
_REPOSITORY_ROOT = Path(__file__).resolve().parents[4]
_APPROVED_FIXTURE_MANIFEST = (
    _REPOSITORY_ROOT / "tools" / "media-player-stress" / "fixture-manifest.json"
)
_CACHE_ROOT_BOUNDARY = _REPOSITORY_ROOT / "tools" / "media-player-stress" / ".artifacts"
_SOURCE_DESCRIPTOR_SEAL = object()


class MediaStressFixtureDenied(MediaConfigurationError):
    """The explicit staging/test fixture boundary is not satisfied."""

    code = "media_stress_fixture_denied"
    title = "Media stress fixture is unavailable"


@runtime_checkable
class FixtureProviderActivationVerifier(Protocol):
    """Typed verifier for an externally attested provider activation record."""

    def verify_fixture_provider_activation(
        self,
        *,
        authorization_context: MediaAuthorizationContext,
        playback_grant: PlaybackGrantDescriptor,
        environment: str,
        fixture_id: str,
        manifest_sha256: str,
    ) -> bool: ...


@runtime_checkable
class FixturePlaybackGrantVerifier(Protocol):
    """Typed verifier for the existing server-owned playback grant boundary."""

    def verify_fixture_playback_grant(
        self,
        *,
        authorization_context: MediaAuthorizationContext,
        playback_grant: PlaybackGrantDescriptor,
        fixture_id: str,
        source_sha256: str,
        manifest_sha256: str,
        content_type: str,
        width: int,
        height: int,
        duration_seconds: float,
    ) -> bool: ...


@dataclass(frozen=True, slots=True, init=False)
class _StagingTestFixtureSource:
    """Private return type; callers cannot construct an unverified descriptor."""

    fixture_id: str
    local_path: Path
    content_type: str
    width: int
    height: int
    duration_seconds: float
    source_sha256: str
    manifest_sha256: str
    test_only: bool = True
    provider_activation_required: bool = True
    playback_grant_required: bool = True

    def __init__(
        self,
        *,
        fixture_id: str,
        local_path: Path,
        content_type: str,
        width: int,
        height: int,
        duration_seconds: float,
        source_sha256: str,
        manifest_sha256: str,
        _seal: object,
    ) -> None:
        if _seal is not _SOURCE_DESCRIPTOR_SEAL:
            raise TypeError("fixture source descriptors must come from verified composition")
        object.__setattr__(self, "fixture_id", fixture_id)
        object.__setattr__(self, "local_path", local_path)
        object.__setattr__(self, "content_type", content_type)
        object.__setattr__(self, "width", width)
        object.__setattr__(self, "height", height)
        object.__setattr__(self, "duration_seconds", duration_seconds)
        object.__setattr__(self, "source_sha256", source_sha256)
        object.__setattr__(self, "manifest_sha256", manifest_sha256)
        object.__setattr__(self, "test_only", True)
        object.__setattr__(self, "provider_activation_required", True)
        object.__setattr__(self, "playback_grant_required", True)


def _deny(message: str) -> MediaStressFixtureDenied:
    return MediaStressFixtureDenied(message)


def _is_reparse_or_symlink(path: Path) -> bool:
    try:
        information = path.lstat()
    except FileNotFoundError:
        return False
    except OSError as error:
        raise _deny("fixture path cannot be inspected") from error
    if stat.S_ISLNK(information.st_mode):
        return True
    return bool(getattr(information, "st_file_attributes", 0) & 0x0400)


def _reject_any_reparse_components(path: Path) -> None:
    absolute_path = path.absolute()
    current = Path(absolute_path.anchor)
    for component in absolute_path.relative_to(current).parts:
        if _is_reparse_or_symlink(current):
            raise _deny("fixture path contains a symlink or reparse point")
        current = current / component
        if _is_reparse_or_symlink(current):
            raise _deny("fixture path contains a symlink or reparse point")


def _reject_links_between(boundary: Path, target: Path) -> None:
    """Reject symlink/reparse components from boundary through target."""

    raw_boundary = boundary.absolute()
    raw_target = target.absolute()
    try:
        relative = raw_target.relative_to(raw_boundary)
    except ValueError as error:
        raise _deny("fixture path escaped the ignored cache boundary") from error
    if _is_reparse_or_symlink(raw_boundary):
        raise _deny("fixture cache boundary must not be a symlink or reparse point")
    current = raw_boundary
    for part in relative.parts:
        current = current / part
        if _is_reparse_or_symlink(current):
            raise _deny("fixture cache path contains a symlink or reparse point")


def _canonical_cache_root(value: Path) -> Path:
    if not isinstance(value, Path):
        raise TypeError("cache_root must be a pathlib.Path")
    if any(part == ".." for part in value.parts):
        raise _deny("fixture cache root must not contain '..'")
    rendered = str(value)
    if "://" in rendered or any(
        ord(character) < 0x20 or ord(character) == 0x7F for character in rendered
    ):
        raise _deny("fixture cache root must be a local path")
    boundary = _CACHE_ROOT_BOUNDARY.resolve(strict=False)
    _reject_any_reparse_components(_CACHE_ROOT_BOUNDARY)
    raw_value = value.absolute()
    _reject_any_reparse_components(raw_value)
    try:
        raw_value.relative_to(_CACHE_ROOT_BOUNDARY.absolute())
    except ValueError:
        pass
    else:
        _reject_links_between(_CACHE_ROOT_BOUNDARY, raw_value)
    try:
        root = value.resolve(strict=False)
        root.relative_to(boundary)
    except (OSError, ValueError) as error:
        raise _deny(
            "fixture cache root must be the ignored "
            "tools/media-player-stress/.artifacts boundary or a descendant"
        ) from error
    _reject_links_between(boundary, root)
    return root


def _safe_relative(value: Any, *, field_name: str) -> str:
    if (
        not isinstance(value, str)
        or not value.strip()
        or "\\" in value
        or ":" in value
        or any(ord(character) < 0x20 or ord(character) == 0x7F for character in value)
    ):
        raise _deny(f"fixture manifest {field_name} is not a safe relative path")
    normalized = value.strip()
    parts = normalized.split("/")
    if normalized.startswith("/") or any(part in {"", ".", ".."} for part in parts):
        raise _deny(f"fixture manifest {field_name} is not a safe relative path")
    return "/".join(parts)


def _cache_path(root: Path, relative: str) -> Path:
    root = _canonical_cache_root(root)
    try:
        raw_candidate = root / relative
        _reject_any_reparse_components(raw_candidate)
        candidate = raw_candidate.resolve(strict=False)
        candidate.relative_to(root)
    except (OSError, ValueError) as error:
        raise _deny("fixture cache path escaped the ignored cache boundary") from error
    _reject_links_between(root, candidate)
    return candidate


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as stream:
            for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(chunk)
    except OSError as error:
        raise _deny("the local stress fixture cannot be read") from error
    return digest.hexdigest()


def _read_json(path: Path) -> Mapping[str, Any]:
    try:
        raw = path.read_bytes()
    except OSError as error:
        raise _deny("the approved fixture registry cannot be read") from error
    if len(raw) > _MAX_MANIFEST_BYTES:
        raise _deny("the approved fixture registry exceeds its bound")
    try:
        value = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise _deny("the approved fixture registry is not valid UTF-8 JSON") from error
    if not isinstance(value, Mapping):
        raise _deny("the approved fixture registry must be an object")
    return value


def _manifest_string(fixture: Mapping[str, Any], key: str, *, maximum: int = 512) -> str:
    value = fixture.get(key)
    if not isinstance(value, str) or not value.strip() or len(value) > maximum:
        raise _deny(f"fixture manifest field {key} is invalid")
    return value.strip()


def _manifest_sha(fixture: Mapping[str, Any], key: str) -> str:
    value = _manifest_string(fixture, key, maximum=64).lower()
    if _SHA256.fullmatch(value) is None:
        raise _deny(f"fixture manifest field {key} is not a SHA-256 digest")
    return value


def _is_valid_source_index_date(value: object) -> bool:
    if not isinstance(value, str):
        return False
    try:
        date.fromisoformat(value)
    except ValueError:
        return False
    return True


def _load_registry_fixture(fixture_id: str) -> tuple[Mapping[str, Any], str]:
    if not isinstance(fixture_id, str) or _FIXTURE_ID.fullmatch(fixture_id) is None:
        raise _deny("fixture_id is not an approved registry identifier")
    manifest_path = _APPROVED_FIXTURE_MANIFEST.resolve(strict=False)
    if manifest_path != _APPROVED_FIXTURE_MANIFEST:
        raise _deny("fixture registry path is not the approved exact path")
    _reject_any_reparse_components(_APPROVED_FIXTURE_MANIFEST)
    payload = _read_json(manifest_path)
    if payload.get("schema_version") != "ac-media-stress-fixtures.v1":
        raise _deny("fixture registry schema is not approved")
    if payload.get("status") != "test_only":
        raise _deny("fixture registry must remain test_only")
    if payload.get("manifest_updated_at") != "2026-09-07":
        raise _deny("fixture registry update date is not approved")
    generator = payload.get("generator")
    if not isinstance(generator, Mapping) or (
        generator.get("tool") != "ffmpeg"
        or generator.get("source") != "lavfi:testsrc2"
        or generator.get("checksum_pinned") is not True
        or not isinstance(generator.get("version_prefix"), str)
        or not str(generator.get("version_prefix")).startswith("ffmpeg version ")
    ):
        raise _deny("fixture generator policy is not checksum-pinned")
    boundary = payload.get("content_boundary")
    if not isinstance(boundary, Mapping) or boundary.get("cache_root") != (
        "tools/media-player-stress/.artifacts"
    ):
        raise _deny("fixture registry cache boundary is not approved")
    if any(
        boundary.get(key) is not False
        for key in (
            "authority_closers_course_content",
            "canonical_learning_state",
            "provider_activation_bypassed",
            "playback_grant_bypassed",
            "production_enabled",
        )
    ):
        raise _deny("fixture registry content boundary is not fail-closed")
    fixtures = payload.get("fixtures")
    if not isinstance(fixtures, list):
        raise _deny("fixture registry fixtures are missing")
    matches = [
        entry for entry in fixtures if isinstance(entry, Mapping) and entry.get("id") == fixture_id
    ]
    if len(matches) != 1:
        raise _deny("fixture_id is not an exact entry in the approved registry")
    manifest_sha256 = _sha256(manifest_path)
    if manifest_sha256 != _EXPECTED_FIXTURE_MANIFEST_SHA256:
        raise _deny("fixture registry checksum is not the approved immutable record")
    return matches[0], manifest_sha256


def _probe(path: Path) -> Mapping[str, Any]:
    if not path.is_file() or _is_reparse_or_symlink(path):
        raise _deny("the local stress fixture is not a regular file")
    ffprobe = shutil.which("ffprobe")
    if not ffprobe:
        raise _deny("ffprobe is required to verify the stress fixture")
    try:
        result = subprocess.run(  # noqa: S603 - fixed ffprobe argv and shell-free
            [
                ffprobe,
                "-v",
                "error",
                "-print_format",
                "json",
                "-show_streams",
                "-show_format",
                str(path),
            ],
            check=True,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            timeout=60,
            text=True,
        )
        if len(result.stdout.encode("utf-8")) > _MAX_PROBE_BYTES:
            raise _deny("ffprobe metadata exceeds its bound")
        value = json.loads(result.stdout)
    except (OSError, subprocess.SubprocessError, UnicodeError, json.JSONDecodeError) as error:
        raise _deny("ffprobe could not verify the stress fixture") from error
    if not isinstance(value, Mapping):
        raise _deny("ffprobe metadata is not an object")
    return value


def _verify_registry_fixture(
    fixture: Mapping[str, Any], manifest_sha256: str, *, cache_root: Path
) -> _StagingTestFixtureSource:
    fixture_id = _manifest_string(fixture, "id", maximum=80).lower()
    if (
        _FIXTURE_ID.fullmatch(fixture_id) is None
        or fixture.get("course_content") is not False
        or not isinstance(fixture.get("title"), str)
        or not 1 <= len(str(fixture.get("title", "")).strip()) <= 240
    ):
        raise _deny("fixture registry entry is not a test-only fixture")
    kind = fixture.get("kind")
    if kind not in {"external_open_license", "generated_lavfi"}:
        raise _deny("fixture kind is not approved")
    expected_fields = (
        _EXTERNAL_FIXTURE_FIELDS if kind == "external_open_license" else _GENERATED_FIXTURE_FIELDS
    )
    if set(fixture) != expected_fields:
        raise _deny("fixture registry entry fields are not the approved schema")
    content_type = _manifest_string(fixture, "content_type", maximum=96).lower()
    if content_type not in _ALLOWED_CONTENT_TYPES:
        raise _deny("fixture content type is not approved")
    expected_digest = _manifest_sha(fixture, "sha256")
    metadata = fixture.get("metadata")
    if not isinstance(metadata, Mapping):
        raise _deny("fixture metadata is missing")
    width = metadata.get("width")
    height = metadata.get("height")
    duration = metadata.get("duration_seconds")
    tolerance = metadata.get("duration_tolerance_seconds")
    fps = metadata.get("fps")
    video_codec = metadata.get("video_codec")
    container = metadata.get("container")
    audio_codecs = metadata.get("audio_codecs")
    expected_container = {"video/mp4": "mp4", "video/webm": "webm"}[content_type]
    expected_suffix = {"video/mp4": ".mp4", "video/webm": ".webm"}[content_type]
    if (
        isinstance(width, bool)
        or not isinstance(width, int)
        or not 0 < width <= 7680
        or isinstance(height, bool)
        or not isinstance(height, int)
        or not 0 < height <= 4320
        or isinstance(duration, bool)
        or not isinstance(duration, (int, float))
        or not math.isfinite(float(duration))
        or not 0 < float(duration) <= 4 * 60 * 60
        or isinstance(tolerance, bool)
        or not isinstance(tolerance, (int, float))
        or not math.isfinite(float(tolerance))
        or not 0 < float(tolerance) < float(duration)
        or not isinstance(fps, str)
        or _FPS.fullmatch(fps) is None
        or not isinstance(video_codec, str)
        or video_codec.strip().lower() not in _ALLOWED_VIDEO_CODECS
        or container != expected_container
        or not isinstance(audio_codecs, list)
        or any(
            not isinstance(codec, str) or codec.strip().lower() not in _ALLOWED_AUDIO_CODECS
            for codec in audio_codecs
        )
        or len({str(codec).strip().lower() for codec in audio_codecs}) != len(audio_codecs)
    ):
        raise _deny("fixture registry metadata is outside its bounds")
    relative_cache_path = _safe_relative(fixture.get("cache_path"), field_name="cache_path")
    if (
        not relative_cache_path.lower().endswith(expected_suffix)
        or _EXPECTED_CACHE_PATHS.get(fixture_id) != relative_cache_path
    ):
        raise _deny("fixture registry container does not match its content type")
    path = _cache_path(cache_root, relative_cache_path)
    try:
        size = path.stat().st_size
    except OSError as error:
        raise _deny("the checked-in fixture is not present in the configured cache") from error
    if not path.is_file() or size <= 0 or size > _MAX_FIXTURE_BYTES:
        raise _deny("the checked-in fixture is not a bounded regular file")
    if _sha256(path) != expected_digest:
        raise _deny("fixture source checksum does not match the approved registry")
    if kind == "external_open_license":
        source_url = fixture.get("source_url")
        expected_provenance = (
            _EXPECTED_EXTERNAL_PROVENANCE.get(source_url) if isinstance(source_url, str) else None
        )
        if (
            source_url not in _SOURCE_URLS
            or fixture.get("source_page") not in _SOURCE_PAGE_URLS
            or fixture.get("source_index") not in _SOURCE_INDEX_URLS
            or fixture.get("license_url") not in _LICENSE_URLS
            or "Creative Commons" not in str(fixture.get("license", ""))
            or re.fullmatch(
                r"[0-9]{4}-[0-9]{2}-[0-9]{2}",
                str(fixture.get("source_index_date", "")),
            )
            is None
            or _is_valid_source_index_date(fixture.get("source_index_date")) is False
            or _manifest_string(fixture, "source_date_basis", maximum=240)
            != "official Blender download directory listing; not asserted as HTTP Last-Modified"
            or expected_provenance is None
            or any(fixture.get(key) != value for key, value in expected_provenance.items())
        ):
            raise _deny("fixture provenance is not an exact approved source record")
        if not _is_valid_source_index_date(fixture.get("retrieved_at")):
            raise _deny("fixture provenance retrieval date is invalid")
        archive_path = _cache_path(
            cache_root,
            _safe_relative(fixture.get("archive_cache_path"), field_name="archive_cache_path"),
        )
        if fixture.get("archive_cache_path") != _EXPECTED_ARCHIVE_CACHE_PATHS.get(fixture_id):
            raise _deny("fixture source archive path is not the exact approved path")
        archive_digest = _manifest_sha(fixture, "archive_sha256")
        approved_member = (
            _EXPECTED_ARCHIVE_MEMBERS.get(source_url) if isinstance(source_url, str) else None
        )
        if fixture.get("archive_member") != approved_member:
            raise _deny("fixture source archive member is not the approved exact member")
        if (
            not archive_path.is_file()
            or _is_reparse_or_symlink(archive_path)
            or _sha256(archive_path) != archive_digest
        ):
            raise _deny("fixture source archive does not match the approved registry")
    else:
        if (
            fixture.get("license") != _EXPECTED_GENERATED_LICENSE
            or fixture.get("license_url") is not None
            or fixture.get("attribution") != _EXPECTED_GENERATED_ATTRIBUTION
        ):
            raise _deny("generated fixture license/provenance is not an exact synthetic record")
        args = fixture.get("ffmpeg_args")
        if (
            not isinstance(args, list)
            or not args
            or any(not isinstance(argument, str) or not argument for argument in args)
            or args[:2] != ["-nostdin", "-hide_banner"]
            or args.count("-f") != 1
            or args.count("-i") != 1
            or args.count("-t") != 1
        ):
            raise _deny("generated fixture FFmpeg source is not approved")
        if tuple(args) != _EXPECTED_GENERATED_FFMPEG_ARGS.get(fixture_id):
            raise _deny("generated fixture FFmpeg args are not the exact approved lavfi allowlist")
        try:
            format_index = args.index("-f")
            input_index = args.index("-i")
            duration_index = args.index("-t")
            input_value = args[input_index + 1]
            duration_value = float(args[duration_index + 1])
        except (IndexError, TypeError, ValueError) as error:
            raise _deny("generated fixture FFmpeg source is not approved") from error
        source_match = re.fullmatch(r"testsrc2=size=(\d+)x(\d+):rate=(\d+)", input_value)
        if (
            args[format_index + 1] != "lavfi"
            or source_match is None
            or not math.isfinite(duration_value)
            or duration_value <= 0
            or duration_value > 2 * 60 * 60
            or any(
                any(
                    token in argument.lower()
                    for token in (
                        "http",
                        "https",
                        "file:",
                        "concat",
                        "-filter_complex",
                        "-map",
                        "-attach",
                    )
                )
                for argument in args
            )
        ):
            raise _deny("generated fixture FFmpeg source is not approved")
        source_width, source_height, source_fps = (int(value) for value in source_match.groups())
        if (
            source_width != width
            or source_height != height
            or f"{source_fps}/1" != fps
            or duration_value != float(duration)
        ):
            raise _deny("generated FFmpeg source does not match fixture metadata")
    metadata_probe = _probe(path)
    streams = metadata_probe.get("streams")
    if not isinstance(streams, list):
        raise _deny("ffprobe returned no stream inventory")
    videos = [
        stream
        for stream in streams
        if isinstance(stream, Mapping) and stream.get("codec_type") == "video"
    ]
    audios = [
        stream
        for stream in streams
        if isinstance(stream, Mapping) and stream.get("codec_type") == "audio"
    ]
    if len(videos) != 1:
        raise _deny("fixture must contain exactly one video stream")
    video = videos[0]
    actual_audio = sorted(str(stream.get("codec_name", "")).lower() for stream in audios)
    expected_audio = sorted(str(codec).lower() for codec in audio_codecs)
    if (
        video.get("codec_name") != video_codec
        or video.get("width") != width
        or video.get("height") != height
        or video.get("r_frame_rate") != fps
        or actual_audio != expected_audio
    ):
        raise _deny("ffprobe metadata does not match the approved registry")
    format_metadata = metadata_probe.get("format")
    if not isinstance(format_metadata, Mapping):
        raise _deny("ffprobe format metadata is missing")
    format_name = str(format_metadata.get("format_name", "")).lower()
    if container == "mp4" and not format_name.startswith("mov,mp4"):
        raise _deny("ffprobe container does not match the approved content type")
    if container == "webm" and "webm" not in format_name:
        raise _deny("ffprobe container does not match the approved content type")
    try:
        actual_duration = float(format_metadata["duration"])
    except (KeyError, TypeError, ValueError) as error:
        raise _deny("ffprobe duration is not measurable") from error
    if not math.isfinite(actual_duration) or abs(actual_duration - float(duration)) > float(
        tolerance
    ):
        raise _deny("ffprobe duration does not match the approved registry")
    return _StagingTestFixtureSource(
        fixture_id=fixture_id,
        local_path=path,
        content_type=content_type,
        width=width,
        height=height,
        duration_seconds=float(duration),
        source_sha256=expected_digest,
        manifest_sha256=manifest_sha256,
        _seal=_SOURCE_DESCRIPTOR_SEAL,
    )


def _verify_typed_gate(
    verifier: object,
    protocol: type[object],
    method_name: str,
    **kwargs: object,
) -> None:
    if not isinstance(verifier, protocol):
        raise _deny("a typed media authorization verifier is required")
    method = getattr(verifier, method_name, None)
    if not callable(method):
        raise _deny("a typed media authorization verifier is required")
    try:
        verified = method(**kwargs)
    except Exception as error:  # noqa: BLE001 - fail closed at the app boundary
        raise _deny("media authorization verifier failed") from error
    if verified is not True:
        raise _deny("media authorization verifier did not attest the fixture")


def _verify_playback_scope(
    authorization_context: object, playback_grant: object
) -> tuple[MediaAuthorizationContext, PlaybackGrantDescriptor]:
    """Require the server-created opaque scope before calling an external verifier."""

    if not isinstance(authorization_context, MediaAuthorizationContext):
        raise _deny("a server-created media authorization context is required")
    if not isinstance(playback_grant, PlaybackGrantDescriptor):
        raise _deny("a server-created playback grant is required")
    if playback_grant.authorization != authorization_context:
        raise _deny("playback grant authorization context does not match")
    return authorization_context, playback_grant


def compose_staging_test_fixture_source(
    *,
    environment: str,
    enabled: bool,
    fixture_id: str,
    cache_root: Path,
    provider_activation_verifier: FixtureProviderActivationVerifier,
    playback_grant_verifier: FixturePlaybackGrantVerifier,
    authorization_context: MediaAuthorizationContext,
    playback_grant: PlaybackGrantDescriptor,
) -> _StagingTestFixtureSource:
    """Return a verified local fixture only after all staging/test gates pass."""

    if environment == "production":
        raise _deny("production cannot compose media stress fixtures")
    if environment not in _ALLOWED_ENVIRONMENTS:
        raise _deny("media stress fixtures require test, development, or staging environment")
    if enabled is not True:
        raise _deny("media stress fixtures require explicit opt-in")
    root = _canonical_cache_root(cache_root)
    fixture, manifest_sha256 = _load_registry_fixture(fixture_id)
    source = _verify_registry_fixture(fixture, manifest_sha256, cache_root=root)
    authorization_context, playback_grant = _verify_playback_scope(
        authorization_context, playback_grant
    )
    _verify_typed_gate(
        provider_activation_verifier,
        FixtureProviderActivationVerifier,
        "verify_fixture_provider_activation",
        authorization_context=authorization_context,
        playback_grant=playback_grant,
        environment=environment,
        fixture_id=source.fixture_id,
        manifest_sha256=source.manifest_sha256,
    )
    _verify_typed_gate(
        playback_grant_verifier,
        FixturePlaybackGrantVerifier,
        "verify_fixture_playback_grant",
        authorization_context=authorization_context,
        playback_grant=playback_grant,
        fixture_id=source.fixture_id,
        source_sha256=source.source_sha256,
        manifest_sha256=source.manifest_sha256,
        content_type=source.content_type,
        width=source.width,
        height=source.height,
        duration_seconds=source.duration_seconds,
    )
    return source


def compose_staging_test_fixture_source_from_settings(
    settings: Any,
    *,
    fixture_id: str,
    provider_activation_verifier: FixtureProviderActivationVerifier,
    playback_grant_verifier: FixturePlaybackGrantVerifier,
    authorization_context: MediaAuthorizationContext,
    playback_grant: PlaybackGrantDescriptor,
) -> _StagingTestFixtureSource:
    """Use the validated settings cache root; callers cannot override it."""

    environment = getattr(settings, "environment", None)
    enabled = getattr(settings, "media_stress_fixtures_enabled", False)
    configured_root = getattr(settings, "media_stress_fixtures_cache_root", None)
    if not isinstance(environment, str):
        raise _deny("fixture settings have no valid environment")
    if not isinstance(configured_root, str) or not configured_root.strip():
        raise _deny("fixture settings have no configured cache root")
    return compose_staging_test_fixture_source(
        environment=environment,
        enabled=enabled,
        fixture_id=fixture_id,
        cache_root=Path(configured_root.strip()),
        provider_activation_verifier=provider_activation_verifier,
        playback_grant_verifier=playback_grant_verifier,
        authorization_context=authorization_context,
        playback_grant=playback_grant,
    )


__all__ = [
    "FixturePlaybackGrantVerifier",
    "FixtureProviderActivationVerifier",
    "MediaStressFixtureDenied",
    "compose_staging_test_fixture_source",
    "compose_staging_test_fixture_source_from_settings",
]
