#!/usr/bin/env sh
set -eu

: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${AC_DB_MIGRATOR_PASSWORD:?AC_DB_MIGRATOR_PASSWORD is required}"
: "${AC_DB_RUNTIME_PASSWORD:?AC_DB_RUNTIME_PASSWORD is required}"
: "${AC_DB_BACKUP_PASSWORD:?AC_DB_BACKUP_PASSWORD is required}"

psql \
  --set ON_ERROR_STOP=1 \
  --set migrator_password="$AC_DB_MIGRATOR_PASSWORD" \
  --set runtime_password="$AC_DB_RUNTIME_PASSWORD" \
  --set backup_password="$AC_DB_BACKUP_PASSWORD" \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<'SQL'
CREATE ROLE ac_migrator LOGIN PASSWORD :'migrator_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE ac_runtime LOGIN PASSWORD :'runtime_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE ac_backup LOGIN PASSWORD :'backup_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;

GRANT CONNECT ON DATABASE ac_platform TO ac_migrator, ac_runtime, ac_backup;
GRANT USAGE, CREATE ON SCHEMA public TO ac_migrator;
GRANT USAGE ON SCHEMA public TO ac_runtime, ac_backup;

ALTER DEFAULT PRIVILEGES FOR ROLE ac_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ac_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE ac_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO ac_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE ac_migrator IN SCHEMA public
  GRANT SELECT ON TABLES TO ac_backup;
ALTER DEFAULT PRIVILEGES FOR ROLE ac_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO ac_backup;
SQL
