\set ON_ERROR_STOP on

CREATE ROLE ac_migrator LOGIN PASSWORD 'local-migrator-only' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE ac_runtime LOGIN PASSWORD 'local-runtime-only' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE ac_backup LOGIN PASSWORD 'local-backup-only' NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT CONNECT ON DATABASE ac_platform TO ac_migrator, ac_runtime, ac_backup;
GRANT USAGE, CREATE ON SCHEMA public TO ac_migrator;
GRANT USAGE ON SCHEMA public TO ac_runtime, ac_backup;
ALTER DEFAULT PRIVILEGES FOR ROLE ac_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ac_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE ac_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO ac_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE ac_migrator IN SCHEMA public
  GRANT SELECT ON TABLES TO ac_backup;
